name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: ":boom: Breaking Changes"
    semver-increment: major
    when:
      label: "breaking"
  - title: ":rocket: Features"
    semver-increment: minor
    when:
      label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    semver-increment: minor
    when:
      label: "removal"
  - title: ":beetle: Fixes"
    when:
      label: "bug"
  - title: ":racehorse: Performance"
    when:
      label: "performance"
  - title: ":rotating_light: Testing"
    when:
      label: "testing"
  - title: ":construction_worker: Continuous Integration"
    when:
      labels:
        - "ci"
        - "github_actions"
  - title: ":books: Documentation"
    when:
      label: "documentation"
  - title: ":hammer: Refactoring"
    when:
      label: "refactoring"
  - title: ":lipstick: Style"
    when:
      label: "style"
  - title: ":package: Dependencies"
    when:
      labels:
        - "dependencies"
        - "build"
  # everything else still bumps the patch version
  - type: "version-resolver"
    semver-increment: "patch"
change-template: "- $TITLE (#$NUMBER) $AUTHORS"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES

exclude-contributors:
  - 'Dependabot'
