ci:                                                                                                                                                                                                                                           
  autoupdate_commit_msg: 'chore: update pre-commit hooks'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: '''(/(^ext_libs\/clibpdf\/.*|.+\.y|.+\.r)$)'''
        types: [python, yaml, toml, markdown, json]
        stages: [pre-commit, pre-push, manual]
      - id: mixed-line-ending
        exclude: '''(/(^ext_libs\/clibpdf\/.*|.+\.y|.+\.r)$)'''
        types: [python, yaml, toml, markdown, json, c, c++]
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: '^python/tests/fixtures/'
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: '''(/(^ext_libs\/clibpdf\/.*|.+\.y|.+\.r)$)'''
        types: [python, yaml, toml, markdown, json]
        stages: [pre-commit, pre-push, manual]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.8"
    hooks:
      - id: ruff
        args: [ --fix, --show-fixes ]
        types: [ python ]
      - id: ruff-format
        types: [ python ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        name: pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        language: system
        types: [python]
        args: [--py310-plus]
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"  # Use the latest version which adds inline ignore support
    hooks:
      - id: codespell
        types: [python]
        additional_dependencies:
          - tomli
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.24.1"
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    - id: python-use-type-annotations
  # not ready for mypy
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.10.0"
  #   hooks:
  #     - id: mypy
  #       types: [python]
  #       additional_dependencies: ["numpy"]
  #       pass_filenames: false
  # - repo: https://github.com/scientific-python/cookie
  #   rev: 2024.04.23
  #   hooks:
  #     - id: sp-repo-review 
